AWSTemplateFormatVersion: '2010-09-09'
Description: 'citeit-app

  SAM Template for citeit-app

  '
Globals:
  Function:
    Timeout: 20
Outputs:
  CiteItApi:
    Description: API Gateway endpoint URL for Prod stage for CiteIt function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/citeit/
  CiteItFunction:
    Description: CiteIt Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CiteItFunction
      - Arn
  CiteItFunctionIamRole:
    Description: Implicit IAM Role created for CiteIt function
    Value:
      Fn::GetAtt:
      - CiteItFunctionRole
      - Arn
Resources:
  CiteItFunction:
    Properties:
      CodeUri: s3://read.citeit.net/2af8cd7951c2e2f8800f4350d0aba8a5
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        CiteIt:
          Properties:
            Method: get
            Path: /citeit
          Type: Api
      Handler: app.lambda_handler
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
